@startmindmap
* Управление арендой музыкальных инструментов
** Управление пользователями
*** Авторизация
*** Регистрация сотрудников
*** Смена пароля
** Управление инвентарем
*** Добавление инструмента
*** Редактирование инструмента
*** Изменение статуса
** Управление клиентами
*** Регистрация
*** Редактирование
*** Деактивация
** Управление арендой
*** Создание аренды
*** Продление аренды
*** Завершение аренды
** Управление договорами
*** Генерация номера договора
*** Хранение и просмотр
** Управление платежами
*** Регистрация оплаты
*** Контроль задолженности
** Отчетность
*** Доходы за период
*** Доступность инструментов
*** Задолженности
*** Активность клиентов
@endmindmap
